//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TACTIVIDIARIACOB
    {
        public string ccompany { get; set; }
        public string c_zona { get; set; }
        public decimal ccliente { get; set; }
        public byte cdiasemana { get; set; }
        public System.DateTime cfecha { get; set; }
        public string ctipodocument { get; set; }
        public Nullable<decimal> cnumdocu { get; set; }
        public Nullable<byte> ccanctotal { get; set; }
        public Nullable<byte> ccancabono { get; set; }
        public Nullable<decimal> cdesctopp { get; set; }
        public Nullable<decimal> cdescto1 { get; set; }
        public Nullable<decimal> cnotacred1 { get; set; }
        public Nullable<decimal> cnotacred2 { get; set; }
        public Nullable<decimal> cnotacred3 { get; set; }
        public Nullable<byte> cretencioniva { get; set; }
        public string cnumcomproclie { get; set; }
        public Nullable<decimal> cnumercontrol { get; set; }
        public Nullable<decimal> cmontcompretiva { get; set; }
        public Nullable<byte> crelacionado { get; set; }
    }
}
