//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TBANCO
    {
        public string ccompany { get; set; }
        public string cbanco { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<byte> cactive { get; set; }
        public string cname { get; set; }
        public string cphone1 { get; set; }
        public string cphone2 { get; set; }
        public string cinfocont1 { get; set; }
        public string cinfocont2 { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
