//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCONFIGUSER
    {
        public Nullable<decimal> ccodgerarea { get; set; }
        public Nullable<decimal> ccoddirector { get; set; }
        public Nullable<decimal> ccodproveedor { get; set; }
        public Nullable<decimal> ccodgercomer { get; set; }
        public Nullable<decimal> ccodvendedor { get; set; }
        public Nullable<decimal> ccodadmin { get; set; }
        public Nullable<decimal> ccodsoporte { get; set; }
        public byte ccodcorporativo { get; set; }
        public byte ccodasiscorpo { get; set; }
        public Nullable<byte> ccodgerenciacorporativa { get; set; }
    }
}
