//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCALENDCONT
    {
        public decimal idcalen { get; set; }
        public string ccompany { get; set; }
        public decimal cmontacco { get; set; }
        public decimal cyearacco { get; set; }
        public decimal csemcalend { get; set; }
        public decimal cdiacalend_cal { get; set; }
        public decimal cdiacalend_reg { get; set; }
        public Nullable<byte> cseleccionado { get; set; }
        public Nullable<byte> cmesindicado { get; set; }
        public Nullable<decimal> cmesubicado { get; set; }
        public System.DateTime cdiafecha_cal { get; set; }
        public Nullable<System.DateTime> cdiafecha_reg { get; set; }
        public Nullable<System.DateTime> clun_fec_cal { get; set; }
        public Nullable<System.DateTime> cmar_fec_cal { get; set; }
        public Nullable<System.DateTime> cmier_fec_cal { get; set; }
        public Nullable<System.DateTime> cjuev_fec_cal { get; set; }
        public Nullable<System.DateTime> cvie_fec_cal { get; set; }
        public Nullable<System.DateTime> csab_fec_cal { get; set; }
        public Nullable<System.DateTime> cdom_fec_cal { get; set; }
        public Nullable<System.DateTime> clun_fec_reg { get; set; }
        public Nullable<System.DateTime> cmar_fec_reg { get; set; }
        public Nullable<System.DateTime> cmier_fec_reg { get; set; }
        public Nullable<System.DateTime> cjuev_fec_reg { get; set; }
        public Nullable<System.DateTime> cvie_fec_reg { get; set; }
        public Nullable<System.DateTime> csab_fec_reg { get; set; }
        public Nullable<System.DateTime> cdom_fec_reg { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public string cuserdel { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public decimal cmescalend { get; set; }
        public decimal canocalend { get; set; }
        public Nullable<decimal> cmesprorroga { get; set; }
        public Nullable<decimal> canoprorroga { get; set; }
        public Nullable<byte> cprorroga { get; set; }
        public Nullable<decimal> cmesprorrogacob { get; set; }
        public Nullable<decimal> canoprorrogacob { get; set; }
        public Nullable<byte> cprorrogacob { get; set; }
        public Nullable<byte> cbloqrutapedido { get; set; }
        public Nullable<byte> cbloqaprobpedido { get; set; }
    }
}
