//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCOMPANY
    {
        public string ccompany { get; set; }
        public string cname { get; set; }
        public string caddress { get; set; }
        public string cnamel { get; set; }
        public string caddressl { get; set; }
        public string cphone1 { get; set; }
        public string cphone2 { get; set; }
        public string cfax1 { get; set; }
        public string cfax2 { get; set; }
        public string cemail { get; set; }
        public string cwww { get; set; }
        public string ccodepost { get; set; }
        public string ccountry { get; set; }
        public string crif { get; set; }
        public string cnit { get; set; }
        public string clogo { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public string ctip_contribuy { get; set; }
        public string cservidor { get; set; }
        public string cuserserver { get; set; }
        public string cpasswserver { get; set; }
        public string cdominioemail { get; set; }
        public string calmacenpre { get; set; }
        public string calmacenmme { get; set; }
        public string cabreviado { get; set; }
        public string cnameserver { get; set; }
        public string ccodemisor { get; set; }
        public string ccodreceptor { get; set; }
        public string cconmsg { get; set; }
        public string cnamecod { get; set; }
        public string clocalizacion { get; set; }
        public string ccodclienteprovee { get; set; }
        public Nullable<byte> ctestvelocidad { get; set; }
        public Nullable<byte> ccobroscamion { get; set; }
        public Nullable<byte> cbloqueocrp { get; set; }
    }
}
