//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCONFIGCXC
    {
        public string ccompany { get; set; }
        public string ctipdocfact { get; set; }
        public string ctipdoccheqdev { get; set; }
        public string ctipdocnotdeb { get; set; }
        public string ctipdocnotcred { get; set; }
        public string ctipdoccheq { get; set; }
        public string ctipdocrelcob { get; set; }
        public string ctipdocumentdep { get; set; }
        public string ctipdoccaja { get; set; }
        public string ccuentacheqdia { get; set; }
        public string ccuentacheqtransito { get; set; }
        public string ccuentacheqdevuelto { get; set; }
        public string ccuentadescuentos { get; set; }
        public string ccuentaivareten { get; set; }
        public string ccuentaiva { get; set; }
        public string ccuentacxc { get; set; }
        public string ctypcompro { get; set; }
        public string cconceptocomp { get; set; }
        public string cfpagocheqdev { get; set; }
        public Nullable<decimal> cporcsobregiro { get; set; }
        public string cusergerf { get; set; }
        public Nullable<decimal> cmargengubernamental { get; set; }
    }
}
