//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCONFIGCONSSA
    {
        public string cidsistema { get; set; }
        public string cclavemaestra { get; set; }
        public Nullable<decimal> ccantpedidos { get; set; }
        public Nullable<decimal> cmotivodescpp { get; set; }
        public string ctipocanalemp { get; set; }
        public string ctipocanalcomr { get; set; }
        public System.DateTime cfechamtto { get; set; }
        public Nullable<decimal> ccantidadutmin { get; set; }
        public Nullable<byte> cbloqueruta { get; set; }
        public Nullable<decimal> cpvjustomaxcant { get; set; }
    }
}
