//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCANAL
    {
        public string ccanal { get; set; }
        public string cname { get; set; }
        public Nullable<byte> c_nuevo_web { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> clistaprecio { get; set; }
        public Nullable<byte> cprecio { get; set; }
        public Nullable<byte> cllevaobs { get; set; }
    }
}
