//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCOTPEDFACD
    {
        public string ccompany { get; set; }
        public decimal ccotizacion { get; set; }
        public decimal cpedido { get; set; }
        public decimal cfactura { get; set; }
        public string cproducto { get; set; }
        public string cproveedor { get; set; }
        public string cgrupo { get; set; }
        public string csku { get; set; }
        public Nullable<double> cunidades { get; set; }
        public Nullable<double> cempaques { get; set; }
        public Nullable<double> cdesc1 { get; set; }
        public Nullable<double> cdesc2 { get; set; }
        public Nullable<double> cdesc3 { get; set; }
        public Nullable<double> c_montotot_si { get; set; }
        public Nullable<double> c_impuesto { get; set; }
        public Nullable<double> ccostobruto_u1 { get; set; }
        public Nullable<double> ccostoneto_u1 { get; set; }
        public Nullable<double> ccostobruto_u2 { get; set; }
        public Nullable<double> ccostoneto_u2 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> iddetped { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public string csubgrupo { get; set; }
        public Nullable<decimal> cpreciounitario { get; set; }
        public Nullable<byte> ctipoalimento { get; set; }
        public Nullable<decimal> cprecioventamax { get; set; }
        public Nullable<byte> replicado { get; set; }
    }
}
