//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCOTPEDFACMMOVILIZZ
    {
        public System.Guid cpedidomovilizz { get; set; }
        public decimal ccodigopedidomovilizz { get; set; }
        public decimal cpedido { get; set; }
        public System.DateTime cfecha { get; set; }
        public string cvendedor { get; set; }
        public Nullable<decimal> ccliente { get; set; }
        public string ccompany { get; set; }
    }
}
