//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCLIENTE
    {
        public string cgroupcomp { get; set; }
        public decimal ccliente { get; set; }
        public string c_rif { get; set; }
        public string c_nit { get; set; }
        public string c_nomb_comer { get; set; }
        public string c_municipio { get; set; }
        public string c_parroquia { get; set; }
        public string c_sector { get; set; }
        public string c_urbanizacion { get; set; }
        public string c_carretera { get; set; }
        public string c_avenida { get; set; }
        public string c_calle { get; set; }
        public string c_carrera { get; set; }
        public string c_transversal { get; set; }
        public string c_esquina { get; set; }
        public string c_piso { get; set; }
        public string c_edificio { get; set; }
        public string c_local { get; set; }
        public string c_preferencia { get; set; }
        public string c_pcardinal { get; set; }
        public string c_estado { get; set; }
        public string c_ciudad { get; set; }
        public string c_direcc_fiscal { get; set; }
        public string c_telefono { get; set; }
        public string c_fax { get; set; }
        public string c_email { get; set; }
        public string c_www { get; set; }
        public string c_inf_replegal { get; set; }
        public Nullable<System.DateTime> c_fech_inicio { get; set; }
        public Nullable<System.DateTime> c_fech_ultvisita { get; set; }
        public Nullable<System.DateTime> c_fech_ultfactura { get; set; }
        public string c_tip_contribuy { get; set; }
        public string c_saldo { get; set; }
        public string c_estatus_cob { get; set; }
        public string c_limt_credit { get; set; }
        public string c_lun_visita { get; set; }
        public string c_mar_visita { get; set; }
        public string c_mie_visita { get; set; }
        public string c_jue_visita { get; set; }
        public string c_vie_visita { get; set; }
        public string c_sab_visita { get; set; }
        public string c_dom_visita { get; set; }
        public string c_lun_despa { get; set; }
        public string c_mar_despa { get; set; }
        public string c_mie_despa { get; set; }
        public string c_jue_despa { get; set; }
        public string c_vie_despa { get; set; }
        public string c_sab_despa { get; set; }
        public string c_dom_despa { get; set; }
        public Nullable<byte> c_activo { get; set; }
        public Nullable<System.DateTime> c_fecha_inactivo { get; set; }
        public string c_descuen_esp { get; set; }
        public string c_clasifica { get; set; }
        public string c_casa_matriz { get; set; }
        public string c_info_cont_1 { get; set; }
        public string c_info_cont_2 { get; set; }
        public string c_info_cont_3 { get; set; }
        public string c_notas { get; set; }
        public string c_zona { get; set; }
        public string c_estable { get; set; }
        public string c_canal { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public Nullable<byte> c_nuevo_web { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public Nullable<byte> c_edit_2 { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> c_num_pedi { get; set; }
        public string c_razsocial_1 { get; set; }
        public string c_razsocial_2 { get; set; }
        public Nullable<System.DateTime> c_fecha_reactivacion { get; set; }
        public string c_notasinactivo { get; set; }
        public string cfpago { get; set; }
        public string c_notasreactivacion { get; set; }
        public string c_bloquin { get; set; }
        public string c_banco_neg { get; set; }
        public string c_banco_per { get; set; }
        public string c_banco_soc { get; set; }
        public string c_cuenta_neg { get; set; }
        public string c_cuenta_per { get; set; }
        public string c_cuenta_soc { get; set; }
        public Nullable<byte> c_especial { get; set; }
        public string c_refcomercial1 { get; set; }
        public string c_refcomercial2 { get; set; }
        public string c_refcomercial3 { get; set; }
        public string c_localstatus { get; set; }
        public Nullable<byte> c_seguro { get; set; }
        public Nullable<decimal> c_diascalle { get; set; }
        public Nullable<decimal> c_cheqdevuel { get; set; }
        public Nullable<decimal> c_tiemposodica { get; set; }
        public Nullable<byte> c_frecucompra { get; set; }
        public Nullable<decimal> c_promcompra { get; set; }
        public Nullable<decimal> c_montomenor { get; set; }
        public Nullable<decimal> c_montomayor { get; set; }
        public string c_nombaccprin { get; set; }
        public Nullable<byte> c_balancegen { get; set; }
        public Nullable<byte> c_estganyper { get; set; }
        public Nullable<byte> c_otrosef { get; set; }
        public Nullable<byte> c_regmercantil { get; set; }
        public Nullable<byte> c_riffoto { get; set; }
        public Nullable<byte> c_nitfoto { get; set; }
        public Nullable<byte> c_cedfoto { get; set; }
        public string c_notascob { get; set; }
        public string c_clientesigesod { get; set; }
        public string c_clientesigemog { get; set; }
        public Nullable<System.DateTime> c_fechainical { get; set; }
        public string c_tipvisita { get; set; }
        public Nullable<decimal> c_numlientean { get; set; }
        public Nullable<byte> c_atendidodirecto { get; set; }
        public string c_nombredirecto { get; set; }
        public Nullable<byte> c_constitulegal { get; set; }
        public Nullable<decimal> c_numacciones { get; set; }
        public Nullable<decimal> c_capitalsolreg { get; set; }
        public Nullable<decimal> c_capitalsolpag { get; set; }
        public Nullable<int> idencuesta { get; set; }
        public Nullable<decimal> c_comprelacio { get; set; }
        public string cclientep { get; set; }
        public Nullable<byte> c_limt_credit_f { get; set; }
        public Nullable<byte> c_cheq_dev_f { get; set; }
        public Nullable<byte> c_fact_venc_f { get; set; }
        public Nullable<int> c_direcc_despa { get; set; }
        public Nullable<byte> cbackorder { get; set; }
        public Nullable<byte> c_bebidas { get; set; }
        public Nullable<byte> cmarcado { get; set; }
        public Nullable<decimal> cidciudad { get; set; }
        public string cciudades { get; set; }
        public Nullable<byte> c_bloqueo_manual { get; set; }
        public string c_bloqueo_manual_usuario { get; set; }
        public Nullable<System.DateTime> c_bloqueo_manual_fecha { get; set; }
        public string c_motivo_bloqueo_manual { get; set; }
        public Nullable<byte> c_listanegra { get; set; }
    }
}
