//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TCOTPEDFACM
    {
        public string ccompany { get; set; }
        public decimal ccotizacion { get; set; }
        public decimal cpedido { get; set; }
        public decimal cfactura { get; set; }
        public string cproceso { get; set; }
        public Nullable<decimal> ccliente { get; set; }
        public Nullable<decimal> cclientep { get; set; }
        public string cvendedor { get; set; }
        public string ccobrador { get; set; }
        public System.DateTime c_fecha_cotiza { get; set; }
        public Nullable<System.DateTime> c_fecha_pedido { get; set; }
        public Nullable<System.DateTime> c_fecha_factura { get; set; }
        public string cfpago { get; set; }
        public Nullable<double> c_montotot_si { get; set; }
        public Nullable<double> c_impuesto { get; set; }
        public Nullable<decimal> cguiadesp { get; set; }
        public Nullable<byte> c_cota_anul { get; set; }
        public Nullable<byte> c_fact_anul { get; set; }
        public Nullable<byte> c_ped_anul { get; set; }
        public string c_cot_obs { get; set; }
        public string c_ped_obs { get; set; }
        public string c_fact_obs { get; set; }
        public Nullable<byte> c_nuevo_web { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public Nullable<byte> c_edit_2 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> cstatus { get; set; }
        public string cobservaciones { get; set; }
        public Nullable<byte> cdescargado { get; set; }
        public string c_estatus_cob { get; set; }
        public string c_obs_cob { get; set; }
        public Nullable<byte> c_bloqbackorder { get; set; }
        public Nullable<byte> c_rechabackorder { get; set; }
        public Nullable<byte> cpedidomobil { get; set; }
        public Nullable<decimal> c_direcc_despa { get; set; }
        public Nullable<byte> c_pendientebackorder { get; set; }
        public string c_zona { get; set; }
        public string cgerarea { get; set; }
        public Nullable<byte> ccomision { get; set; }
        public Nullable<System.DateTime> cfechaaprob { get; set; }
        public string cuseraprob { get; set; }
        public string c_obs_rechazado { get; set; }
        public Nullable<byte> c_rechazado { get; set; }
        public string c_obs_devovend { get; set; }
        public Nullable<byte> c_devuelto { get; set; }
        public Nullable<byte> ctipoalimento { get; set; }
        public Nullable<byte> replicado { get; set; }
    }
}
