//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TDDESPACHOC
    {
        public decimal cgroupcomp { get; set; }
        public decimal ccliente { get; set; }
        public decimal c_direcc_despa { get; set; }
        public string c_direcc_descrip { get; set; }
        public string c_estado { get; set; }
        public string c_ciudad { get; set; }
        public Nullable<byte> cdelete { get; set; }
    }
}
