//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TEXECRUTA
    {
        public string ccompany { get; set; }
        public string c_zona { get; set; }
        public decimal ccliente { get; set; }
        public string cdiasemana { get; set; }
        public System.DateTime cfecha { get; set; }
        public Nullable<System.DateTime> cfechaeje_oc { get; set; }
        public Nullable<System.DateTime> cfechaeje_ov { get; set; }
        public Nullable<byte> c_aplazopago { get; set; }
        public Nullable<byte> c_otrodiapedido { get; set; }
        public Nullable<byte> c_otrosv { get; set; }
        public Nullable<byte> c_otrosc { get; set; }
        public string c_notav { get; set; }
        public string c_notac { get; set; }
        public string c_notaexodia { get; set; }
        public string c_notaexapago { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
