//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TFACTURAM
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public decimal cfactura { get; set; }
        public decimal cpfactura { get; set; }
        public Nullable<decimal> ccliente { get; set; }
        public string cvendedor { get; set; }
        public Nullable<System.DateTime> c_fecha_pedido { get; set; }
        public Nullable<System.DateTime> c_fecha_factura { get; set; }
        public string cfpago { get; set; }
        public Nullable<decimal> c_montotot_si_bs { get; set; }
        public Nullable<decimal> c_impuesto_bs { get; set; }
        public Nullable<byte> c_fact_anul { get; set; }
        public string c_ped_obs { get; set; }
        public string c_fact_obs { get; set; }
        public string c_estatus_cob { get; set; }
        public string c_obs_cob { get; set; }
        public Nullable<byte> c_impresa { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> c_direcc_despa { get; set; }
        public Nullable<decimal> c_montotot_si_bsf { get; set; }
        public Nullable<decimal> c_impuesto_bsf { get; set; }
        public Nullable<decimal> cprecarga { get; set; }
        public Nullable<decimal> c_numerocontrol { get; set; }
        public Nullable<byte> c_factdevuelta { get; set; }
        public Nullable<byte> c_entregacliente { get; set; }
        public Nullable<decimal> cpedido { get; set; }
        public string c_estado { get; set; }
        public string c_ciudad { get; set; }
        public Nullable<System.DateTime> cfechaanul { get; set; }
        public string cvendedorc { get; set; }
        public string cgerarea { get; set; }
    }
}
