//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TFACTURAD
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public decimal cfactura { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> cunidades { get; set; }
        public Nullable<decimal> cempaques { get; set; }
        public Nullable<decimal> cdesc1 { get; set; }
        public Nullable<decimal> cdesc2 { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> c_monto_si_bs { get; set; }
        public Nullable<decimal> c_impuesto_bs { get; set; }
        public Nullable<decimal> ccostobruto_u1_bs { get; set; }
        public Nullable<decimal> ccostoneto_u1_bs { get; set; }
        public Nullable<decimal> ccostobruto_u2_bs { get; set; }
        public Nullable<decimal> ccostoneto_u2_bs { get; set; }
        public Nullable<decimal> c_impuesto_fact { get; set; }
        public Nullable<decimal> cdescpp { get; set; }
        public Nullable<decimal> cdescppmonto { get; set; }
    }
}
