//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TFILTROREGIONALP
    {
        public string ccompany { get; set; }
        public string cproveedor { get; set; }
        public string cgrupo { get; set; }
        public string csubgrupo { get; set; }
        public string csku { get; set; }
        public string cmarca { get; set; }
        public string cproducto { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
