//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3THISTORICOPMV
    {
        public int cidhistorico { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> cpmvp { get; set; }
        public Nullable<decimal> cpmvmc { get; set; }
        public Nullable<decimal> cpmvpi { get; set; }
        public Nullable<decimal> cppm { get; set; }
        public Nullable<byte> cpreciomanejado { get; set; }
        public Nullable<System.DateTime> cfechainicio { get; set; }
        public Nullable<System.DateTime> cfechafinal { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<decimal> ccostobruto_u1 { get; set; }
    }
}
