//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TLOGMARGENEXCEDENTE
    {
        public decimal clogid { get; set; }
        public string cproducto { get; set; }
        public decimal cpedido { get; set; }
        public decimal ccliente { get; set; }
        public decimal cprecioventa { get; set; }
        public Nullable<decimal> ccostoneto { get; set; }
        public Nullable<decimal> ccajaspedidas { get; set; }
        public Nullable<decimal> cunidadespedidas { get; set; }
        public System.DateTime cfecha { get; set; }
        public byte cvistonotificador { get; set; }
        public byte ccorreoenviado { get; set; }
        public Nullable<decimal> cprecioventamaximo { get; set; }
    }
}
