//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TLISTAPRECIOPMV
    {
        public decimal cidlistaprecio { get; set; }
        public string cproducto { get; set; }
        public decimal cprecioventamax { get; set; }
        public decimal clistprecio1 { get; set; }
        public decimal clistprecio2 { get; set; }
        public decimal clistprecio3 { get; set; }
        public decimal clistprecio4 { get; set; }
        public decimal clistprecio5 { get; set; }
        public decimal clistprecio6 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserdel { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public byte cdelete { get; set; }
    }
}
