//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TLISTAOFERTADV
    {
        public decimal cidlistprecio { get; set; }
        public byte ctiplista { get; set; }
        public string cproveedor { get; set; }
        public string cgrupo { get; set; }
        public string csku { get; set; }
        public string csubgrupo { get; set; }
        public string cdescripcion { get; set; }
        public string cproducto { get; set; }
        public string cprodregular { get; set; }
        public string ccodproveedor { get; set; }
        public Nullable<double> ccostobruto_u1 { get; set; }
        public Nullable<double> ccostobruto_u2 { get; set; }
        public Nullable<double> ccostoneto_u1 { get; set; }
        public Nullable<double> ccostoneto_u2 { get; set; }
        public Nullable<double> cdescnetonac { get; set; }
        public Nullable<double> cdesclinnac1 { get; set; }
        public Nullable<double> cdesclinnac2 { get; set; }
        public Nullable<double> cdesclinnac3 { get; set; }
        public Nullable<double> cdesclinnac4 { get; set; }
    }
}
