//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TMOTIVO
    {
        public string cidmotivo { get; set; }
        public string cdescripcion { get; set; }
        public string cconcepto { get; set; }
        public Nullable<byte> cdocumentnd { get; set; }
        public Nullable<byte> cdocumentnc { get; set; }
        public Nullable<byte> cmotivodev { get; set; }
        public Nullable<byte> cmotivodevcheq { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<byte> cajusteentr { get; set; }
        public Nullable<byte> cajustesali { get; set; }
        public Nullable<byte> cmotivodes { get; set; }
        public Nullable<byte> cmotidevfact { get; set; }
        public Nullable<byte> ctransmme { get; set; }
        public Nullable<byte> cdocumentndcc { get; set; }
        public Nullable<byte> cdocumentnccc { get; set; }
        public Nullable<byte> cmotianulfact { get; set; }
        public Nullable<byte> cmotivodevme { get; set; }
        public Nullable<byte> cmotianulnccxp { get; set; }
        public Nullable<byte> cmotianulndcxp { get; set; }
        public Nullable<byte> cmotianulnccxc { get; set; }
        public Nullable<byte> cmotianulndcxc { get; set; }
        public Nullable<byte> cmotiexcecobro { get; set; }
        public Nullable<byte> cexhibicion { get; set; }
        public Nullable<byte> cmotexcpago { get; set; }
    }
}
