//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TNOTADEBICC
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public decimal cidnotadebitocc { get; set; }
        public decimal ccliente { get; set; }
        public string cvendedor { get; set; }
        public string ctipodocument { get; set; }
        public string cnumdocu { get; set; }
        public Nullable<System.DateTime> cfecha { get; set; }
        public string cdescripcion { get; set; }
        public Nullable<decimal> cmontototsi { get; set; }
        public Nullable<decimal> cimpuesto { get; set; }
        public Nullable<decimal> ctotaldocu { get; set; }
        public Nullable<System.DateTime> cfvfnotadebitop { get; set; }
        public Nullable<byte> cdescontada { get; set; }
        public Nullable<byte> canulado { get; set; }
        public Nullable<byte> cactivo { get; set; }
        public Nullable<byte> cimpresa { get; set; }
        public Nullable<decimal> cidcomprob { get; set; }
        public Nullable<decimal> cnumcontrolnd { get; set; }
        public string cnotanulado { get; set; }
        public Nullable<decimal> cidcomprobanul { get; set; }
        public Nullable<decimal> cidnotrecepc { get; set; }
        public Nullable<decimal> cidmotivo { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<System.DateTime> cfechaanul { get; set; }
        public string cvendedorc { get; set; }
        public string cgerarea { get; set; }
    }
}
