//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TPROVEEDOR
    {
        public string cproveedor { get; set; }
        public string c_rif { get; set; }
        public string c_nit { get; set; }
        public Nullable<byte> clinea { get; set; }
        public string c_nomb_comer { get; set; }
        public string c_nomb_fiscal { get; set; }
        public string c_nomb_abreviado { get; set; }
        public string c_direcc_comer { get; set; }
        public string c_direcc_fiscal { get; set; }
        public string c_telefono { get; set; }
        public string c_fax { get; set; }
        public string c_email { get; set; }
        public string c_www { get; set; }
        public string c_inf_replegal { get; set; }
        public Nullable<System.DateTime> c_fech_inicio { get; set; }
        public string c_tip_contribuy { get; set; }
        public Nullable<decimal> c_saldo { get; set; }
        public Nullable<decimal> c_limt_credit { get; set; }
        public string c_lun_visita { get; set; }
        public string c_mar_visita { get; set; }
        public string c_mie_visita { get; set; }
        public string c_jue_visita { get; set; }
        public string c_vie_visita { get; set; }
        public string c_sab_visita { get; set; }
        public string c_dom_visita { get; set; }
        public string c_lun_despa { get; set; }
        public string c_mar_despa { get; set; }
        public string c_mie_despa { get; set; }
        public string c_jue_despa { get; set; }
        public string c_vie_despa { get; set; }
        public string c_sab_despa { get; set; }
        public string c_dom_despa { get; set; }
        public Nullable<byte> c_activo { get; set; }
        public string c_info_cont_1 { get; set; }
        public string c_info_cont_2 { get; set; }
        public string c_info_cont_3 { get; set; }
        public string c_notas { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public Nullable<byte> c_nuevo_web { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public Nullable<byte> c_edit_2 { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> c_num_pedi { get; set; }
        public Nullable<int> c_dia_credito { get; set; }
        public Nullable<decimal> c_des_ppago { get; set; }
        public string ctcount { get; set; }
        public string cauxiliar { get; set; }
        public string c_banco_1 { get; set; }
        public string c_banco_2 { get; set; }
        public string c_banco_3 { get; set; }
        public string c_cuenta_1 { get; set; }
        public string c_cuenta_2 { get; set; }
        public string c_cuenta_3 { get; set; }
        public string c_tipvisita { get; set; }
        public Nullable<decimal> cporcinvendible { get; set; }
        public Nullable<decimal> cporincvolcomp { get; set; }
        public string cgrupovta { get; set; }
        public Nullable<int> c_inventminp { get; set; }
        public Nullable<decimal> cdiasdespa { get; set; }
        public Nullable<decimal> cfrecuenciatmpo { get; set; }
        public Nullable<System.DateTime> c_fech_ultimo { get; set; }
        public string ccompany { get; set; }
        public Nullable<byte> cglobal { get; set; }
        public Nullable<decimal> ccliente { get; set; }
        public string ccatproveedor { get; set; }
        public Nullable<byte> cpjuridica { get; set; }
        public Nullable<byte> cdomiciliada { get; set; }
        public string ctcountcxc { get; set; }
        public Nullable<decimal> cporcenreteniva { get; set; }
        public Nullable<decimal> cpordevmalestado { get; set; }
        public Nullable<byte> cnotarecojo { get; set; }
        public Nullable<decimal> cporcmalsodica { get; set; }
        public Nullable<byte> citt { get; set; }
        public byte c_interfaz_nestle { get; set; }
        public byte c_interfaz_nestle_usuario { get; set; }
        public Nullable<decimal> cfactorinvmin { get; set; }
        public Nullable<decimal> cfactorinvmax { get; set; }
    }
}
