//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TPRODUCTO
    {
        public string cproveedor { get; set; }
        public string cgrupo { get; set; }
        public string csku { get; set; }
        public string cproducto { get; set; }
        public string cpaleta { get; set; }
        public string csector { get; set; }
        public string carea { get; set; }
        public string calmacen { get; set; }
        public string csubgrupo { get; set; }
        public string cprodregular { get; set; }
        public string ccodfabrica { get; set; }
        public string ccodcorrugado { get; set; }
        public string ccodproveedor { get; set; }
        public Nullable<byte> cactivate { get; set; }
        public Nullable<byte> clinea { get; set; }
        public System.DateTime cfechaini { get; set; }
        public string cnamef { get; set; }
        public string cnamei { get; set; }
        public string cinformacion { get; set; }
        public string cpresentacion { get; set; }
        public string cimagen { get; set; }
        public string cunidadma1 { get; set; }
        public Nullable<double> ccontenidoma1 { get; set; }
        public string cunidadma2 { get; set; }
        public Nullable<double> ccontenidoma2 { get; set; }
        public string cunidad2 { get; set; }
        public string cunidadme { get; set; }
        public Nullable<decimal> ccontenidome { get; set; }
        public Nullable<double> caltura { get; set; }
        public Nullable<double> cancho { get; set; }
        public Nullable<double> cprofundidad { get; set; }
        public Nullable<double> calturac { get; set; }
        public Nullable<double> canchoc { get; set; }
        public Nullable<double> cprofundidadc { get; set; }
        public Nullable<decimal> cpesounid1 { get; set; }
        public Nullable<decimal> cpesounid2 { get; set; }
        public Nullable<decimal> cu1xpaleta { get; set; }
        public Nullable<decimal> cu1xcamada { get; set; }
        public byte cimpuesto1 { get; set; }
        public string ctax1 { get; set; }
        public string ctax2 { get; set; }
        public string ctax3 { get; set; }
        public string ctax4 { get; set; }
        public string ctax5 { get; set; }
        public Nullable<byte> ccomision { get; set; }
        public Nullable<byte> ccodebar { get; set; }
        public Nullable<decimal> ccostobruto_u1 { get; set; }
        public Nullable<decimal> ccostoneto_u1 { get; set; }
        public Nullable<decimal> ccostobruto_u2 { get; set; }
        public Nullable<decimal> ccostoneto_u2 { get; set; }
        public Nullable<decimal> ccostpromu1 { get; set; }
        public Nullable<decimal> ccostpromu2 { get; set; }
        public Nullable<decimal> clistprecio1 { get; set; }
        public Nullable<decimal> clistprecio2 { get; set; }
        public Nullable<decimal> clistprecio3 { get; set; }
        public Nullable<decimal> clistprecio4 { get; set; }
        public Nullable<decimal> clistprecio5 { get; set; }
        public Nullable<decimal> cpreciosuge { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<decimal> cexisrealu1 { get; set; }
        public Nullable<decimal> cexisrealu2 { get; set; }
        public Nullable<decimal> cexiscomu1 { get; set; }
        public Nullable<decimal> cexiscomu2 { get; set; }
        public Nullable<decimal> cexisllegar1 { get; set; }
        public Nullable<decimal> cexisllegar2 { get; set; }
        public string ccompany { get; set; }
        public Nullable<decimal> cexisdesp1 { get; set; }
        public Nullable<decimal> cexisdesp2 { get; set; }
        public Nullable<decimal> cstockmi { get; set; }
        public Nullable<decimal> cstockmax { get; set; }
        public Nullable<decimal> cstockped { get; set; }
        public Nullable<decimal> cstockpro { get; set; }
        public Nullable<double> cpreciomin { get; set; }
        public string ctcomision { get; set; }
        public string ccodbarsku { get; set; }
        public Nullable<double> cultcosto { get; set; }
        public string czona { get; set; }
        public string cmarca { get; set; }
        public Nullable<byte> ccodebaru { get; set; }
        public string ccodunidad { get; set; }
        public string ccodeold { get; set; }
        public Nullable<decimal> cdescnetonac { get; set; }
        public Nullable<decimal> cdesclinnac1 { get; set; }
        public Nullable<decimal> cdesclinnac2 { get; set; }
        public Nullable<decimal> cdesclinnac3 { get; set; }
        public Nullable<decimal> cdesclinnac4 { get; set; }
        public Nullable<System.DateTime> cfecexisreal { get; set; }
        public Nullable<System.DateTime> cfecexiscomp { get; set; }
        public Nullable<System.DateTime> cfecexistllegar { get; set; }
        public Nullable<System.DateTime> cfecultcomp_u1 { get; set; }
        public Nullable<decimal> cexisultcomp_u1 { get; set; }
        public Nullable<System.DateTime> cfecpromvta3m { get; set; }
        public Nullable<decimal> cpromvta3m_u1 { get; set; }
        public Nullable<System.DateTime> cfecpromcomp3m { get; set; }
        public Nullable<decimal> cpromcomp3m { get; set; }
        public Nullable<decimal> ccompdelmes { get; set; }
        public Nullable<System.DateTime> cfecvtapmes { get; set; }
        public Nullable<System.DateTime> cfeccompmes { get; set; }
        public Nullable<decimal> cvtadelmes { get; set; }
        public Nullable<System.DateTime> cfecdiarotultcomp { get; set; }
        public Nullable<decimal> cdiarotultcomp { get; set; }
        public Nullable<System.DateTime> cfecinvmin { get; set; }
        public Nullable<decimal> cinvmin { get; set; }
        public Nullable<System.DateTime> cfecdifcontrinv { get; set; }
        public Nullable<decimal> cdifcontrinv { get; set; }
        public Nullable<decimal> cinvmax { get; set; }
        public Nullable<System.DateTime> cfecinvmax { get; set; }
        public Nullable<decimal> cnecinvactual { get; set; }
        public Nullable<System.DateTime> cfecinvactual { get; set; }
        public Nullable<decimal> cnecvactual { get; set; }
        public Nullable<System.DateTime> cfecnecvactual { get; set; }
        public Nullable<System.DateTime> cfecinvsuge { get; set; }
        public Nullable<decimal> cinvsugerido { get; set; }
        public Nullable<decimal> cpedidoprome { get; set; }
        public Nullable<decimal> cpuntoreorden { get; set; }
        public Nullable<decimal> cbackorder { get; set; }
        public string cestratificacion { get; set; }
        public byte ccombogene { get; set; }
        public byte ccombocomp { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public Nullable<byte> c_edit_2 { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public string valido_ { get; set; }
        public string cnotadesact { get; set; }
        public Nullable<decimal> cpreciolista { get; set; }
        public Nullable<decimal> cdescondp1 { get; set; }
        public Nullable<decimal> cdescondp2 { get; set; }
        public Nullable<decimal> cdescondp3 { get; set; }
        public Nullable<decimal> cdescondp4 { get; set; }
        public Nullable<decimal> cdescondp5 { get; set; }
        public Nullable<decimal> clistprecio6 { get; set; }
        public Nullable<byte> cventaund2 { get; set; }
        public string cnamefc { get; set; }
        public Nullable<byte> cdescpp { get; set; }
        public Nullable<byte> cregpmv { get; set; }
        public Nullable<byte> ctempinhabilitar { get; set; }
    }
}
