//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TPRODUCTOPMV
    {
        public int cidproductopmv { get; set; }
        public string ccompany { get; set; }
        public Nullable<int> cidproductod { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> ccostobrutolote { get; set; }
        public Nullable<decimal> ccostonetolote { get; set; }
        public Nullable<decimal> cprecioventamax { get; set; }
        public Nullable<decimal> cexisrealu1 { get; set; }
        public Nullable<decimal> cexisrealu2 { get; set; }
        public Nullable<decimal> cexiscomu1 { get; set; }
        public Nullable<decimal> cexiscomu2 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
