//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRELACCOBDDEPM
    {
        public string ccompany { get; set; }
        public decimal cgroupcomp { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ciddrelacobro_dep { get; set; }
        public string cnumdepo { get; set; }
        public string cbancodepo { get; set; }
        public string cnumcuentadepo { get; set; }
        public Nullable<System.DateTime> cfechadepo { get; set; }
        public Nullable<double> cmontodepo { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public short cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<byte> replicado { get; set; }
        public byte ceditadoaprob { get; set; }
    }
}
