//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRUTAVISITAD
    {
        public string ccompany { get; set; }
        public string c_zona { get; set; }
        public short cdiasemana { get; set; }
        public int ccliente { get; set; }
        public string cpreferencia { get; set; }
        public string cnotasult { get; set; }
        public Nullable<System.DateTime> cfechault { get; set; }
        public Nullable<short> c_nuevo_web { get; set; }
        public Nullable<short> c_edit_1 { get; set; }
        public string choravisita { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<short> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public Nullable<short> cinsidencia { get; set; }
        public Nullable<System.DateTime> cfechainicio { get; set; }
        public string cuserdel { get; set; }
        public string chorault { get; set; }
    }
}
