//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRELACCOBMCONS
    {
        public decimal cidrelacobro { get; set; }
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public Nullable<byte> cstatus { get; set; }
        public string cuseraprobacion { get; set; }
        public Nullable<System.DateTime> cfechastatus { get; set; }
        public string cobservacionrec { get; set; }
    }
}
