//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRELACCOBM
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public short ctipocobro { get; set; }
        public decimal cidrelacobro { get; set; }
        public Nullable<System.DateTime> cfecharela { get; set; }
        public string cobservaciones { get; set; }
        public Nullable<short> caprobado { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public short cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<short> crelalista { get; set; }
        public string ccaja { get; set; }
        public Nullable<byte> coficina { get; set; }
        public Nullable<byte> csaldado { get; set; }
        public string cgerarea { get; set; }
        public string c_zona { get; set; }
        public Nullable<byte> crelafinven { get; set; }
        public Nullable<byte> replicado { get; set; }
        public Nullable<decimal> ccantdetalles { get; set; }
        public byte ceditadoaprob { get; set; }
    }
}
