//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRELACCOBDTC
    {
        public string ccompany { get; set; }
        public decimal cgroupcompany { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ciddrelacobro_tc { get; set; }
        public string ctipotarjeta { get; set; }
        public Nullable<short> ctarjnacioext { get; set; }
        public string cnumtarjeta { get; set; }
        public Nullable<System.DateTime> cfechavenci { get; set; }
        public string cbancoemision { get; set; }
        public string cidentificacion { get; set; }
        public string cnombretarj { get; set; }
        public string ctelefono { get; set; }
        public string cdireccfact { get; set; }
        public string ccodpostal { get; set; }
        public Nullable<double> cmontocancel { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public short cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
