//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TRELACCOBDD
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string ctipodocument { get; set; }
        public decimal cnumdocu { get; set; }
        public decimal cidrelacobro { get; set; }
        public decimal ctipocancelado { get; set; }
        public decimal cidrelaciondetalle { get; set; }
        public Nullable<decimal> cmontodeefectivo { get; set; }
        public decimal cidrelaciondep { get; set; }
        public decimal ccliente { get; set; }
        public Nullable<byte> replicado { get; set; }
        public byte ceditadoaprob { get; set; }
    }
}
