//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TSALDOCLIENTED
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public decimal ccliente { get; set; }
        public string ctipodocument { get; set; }
        public decimal cnumdocu { get; set; }
        public Nullable<System.DateTime> cfechafact { get; set; }
        public Nullable<System.DateTime> cfechaentrega { get; set; }
        public string cfpago { get; set; }
        public Nullable<System.DateTime> cfelimitcobro { get; set; }
        public Nullable<decimal> cmontofactci { get; set; }
        public Nullable<decimal> cmontofactsi { get; set; }
        public Nullable<decimal> csaldofactura { get; set; }
        public Nullable<decimal> cdiasvencfact { get; set; }
        public Nullable<decimal> cdescppago { get; set; }
        public Nullable<byte> cactivo { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<byte> cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
    }
}
