//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TUSER
    {
        public string cuser { get; set; }
        public string cname { get; set; }
        public string cpassw { get; set; }
        public string cposition { get; set; }
        public string cemail { get; set; }
        public string cphone1 { get; set; }
        public string cphone2 { get; set; }
        public Nullable<System.DateTime> cexpire { get; set; }
        public string clocked { get; set; }
        public string cimg { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public Nullable<byte> cadmin { get; set; }
        public string sexo { get; set; }
        public string ccproveedor { get; set; }
        public string cvendedor { get; set; }
        public Nullable<byte> c_soporte { get; set; }
        public Nullable<byte> chdesk { get; set; }
        public Nullable<short> ctype { get; set; }
        public string cnotas { get; set; }
        public string cgroup { get; set; }
        public Nullable<byte> cfirmante { get; set; }
        public byte c_reseteo_clave { get; set; }
        public Nullable<byte> cinbloqueable { get; set; }
        public Nullable<byte> cpabloquear { get; set; }
    }
}
