//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T3TVENDEDOR
    {
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public string cname { get; set; }
        public Nullable<int> ccedula { get; set; }
        public string c_direccion { get; set; }
        public string c_telefono { get; set; }
        public string c_email { get; set; }
        public string c_zona { get; set; }
        public Nullable<byte> c_activo { get; set; }
        public Nullable<byte> c_tipo_vend { get; set; }
        public string cgerarea { get; set; }
        public string c_foto { get; set; }
        public string c_grupo_vta { get; set; }
        public Nullable<byte> c_nuevo_win { get; set; }
        public Nullable<byte> c_edit_1 { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public byte cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public string chostname { get; set; }
        public Nullable<System.DateTime> cfechainact { get; set; }
    }
}
