//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_DETALLERELCOBROS
    {
        public string ccompany { get; set; }
        public decimal cgroupcomp { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ciddrelacobrodep { get; set; }
        public string cnumdepo { get; set; }
        public decimal ciddrelacobro_depd { get; set; }
        public string cefectivocheq { get; set; }
        public string cnumcheque { get; set; }
        public string cbancocheque { get; set; }
        public Nullable<System.DateTime> cfechaemision { get; set; }
        public short cdelete { get; set; }
        public string cbancochq { get; set; }
        public string cbancodepo { get; set; }
        public string cbancodeposito { get; set; }
        public string cmontocheq { get; set; }
        public string cmontodetalle { get; set; }
        public string montonorelacionado { get; set; }
        public Nullable<decimal> ccliente { get; set; }
    }
}
