//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RELACIONFACTURA
    {
        public string ccompany { get; set; }
        public decimal cgroupcompany { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ccliente { get; set; }
        public decimal ciddrelacobro { get; set; }
        public string ctipodocument { get; set; }
        public decimal cnumdocu { get; set; }
        public Nullable<short> ccanctotal { get; set; }
        public Nullable<short> ccancabono { get; set; }
        public Nullable<decimal> cmontocancel { get; set; }
        public Nullable<byte> cpagcontracam { get; set; }
        public Nullable<decimal> cdesctopp { get; set; }
        public Nullable<decimal> cdescto1 { get; set; }
        public Nullable<decimal> cdescto2 { get; set; }
        public Nullable<decimal> cdescto3 { get; set; }
        public Nullable<decimal> cdescto4 { get; set; }
        public Nullable<decimal> cnotacred1 { get; set; }
        public Nullable<decimal> cnotacred2 { get; set; }
        public Nullable<decimal> cnotacred3 { get; set; }
        public Nullable<decimal> cnotacred4 { get; set; }
        public Nullable<decimal> cnotacred5 { get; set; }
        public Nullable<decimal> cnotacred6 { get; set; }
        public Nullable<decimal> cnotacred7 { get; set; }
        public Nullable<decimal> cnotacred8 { get; set; }
        public Nullable<decimal> cnotacred9 { get; set; }
        public Nullable<decimal> cnotacred10 { get; set; }
        public Nullable<byte> cretencioniva { get; set; }
        public string cnumcomproclie { get; set; }
        public Nullable<decimal> cnumercontrol { get; set; }
        public Nullable<decimal> cmontcompretiva { get; set; }
        public Nullable<byte> cformpagdepe { get; set; }
        public Nullable<byte> cformpagdepc { get; set; }
        public Nullable<byte> cformpagdeptc { get; set; }
        public Nullable<byte> cformpagdeptb { get; set; }
        public Nullable<byte> cformpagdepch { get; set; }
        public System.DateTime cdateadd { get; set; }
        public string cuseradd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserupd { get; set; }
        public short cdelete { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public string cuserdel { get; set; }
        public string c_nomb_comer { get; set; }
        public string Cliente { get; set; }
        public string FechaFactura { get; set; }
        public decimal factura { get; set; }
        public decimal CodCliente { get; set; }
        public string cvendedor { get; set; }
        public string cvendedorc { get; set; }
    }
}
