//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RELACIONCHEQUESTRANSITORESUMEN
    {
        public string cbanco { get; set; }
        public string cnumcheque { get; set; }
        public string cfechaemision { get; set; }
        public string cfechadeposito { get; set; }
        public string cmonto { get; set; }
        public decimal ciddrelacobro_cheq { get; set; }
        public string cidrelacobro { get; set; }
        public string ccompany { get; set; }
        public decimal cgroupcomp { get; set; }
    }
}
