//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_RELACCOBD
    {
        public string ccompany { get; set; }
        public decimal cgroupcompany { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ccliente { get; set; }
        public string c_rif { get; set; }
        public string c_nit { get; set; }
        public string c_nomb_comer { get; set; }
        public decimal ciddrelacobro { get; set; }
        public string ctipodocument { get; set; }
        public string ctipodocumentdescrip { get; set; }
        public decimal cnumdocu { get; set; }
        public Nullable<short> ccanctotal { get; set; }
        public Nullable<short> ccancabono { get; set; }
        public Nullable<decimal> cmontocancel { get; set; }
        public Nullable<byte> cpagcontracam { get; set; }
        public Nullable<decimal> cdesctopp { get; set; }
        public Nullable<decimal> cdescto1 { get; set; }
        public Nullable<byte> cretencioniva { get; set; }
        public string cnumcomproclie { get; set; }
        public Nullable<decimal> cnumercontrol { get; set; }
        public Nullable<decimal> cmontcompretiva { get; set; }
        public Nullable<byte> cformpagdepe { get; set; }
        public Nullable<byte> cformpagdepc { get; set; }
        public Nullable<byte> cformpagdeptc { get; set; }
        public Nullable<byte> cformpagdeptb { get; set; }
        public Nullable<byte> cformpagdepch { get; set; }
        public short cdelete { get; set; }
        public string cfecharela { get; set; }
        public Nullable<double> montonc { get; set; }
        public Nullable<short> caprobado { get; set; }
        public Nullable<byte> csaldado { get; set; }
        public Nullable<byte> coficina { get; set; }
        public string ccaja { get; set; }
        public Nullable<short> crelalista { get; set; }
        public string cvendedor { get; set; }
        public Nullable<decimal> cnotacred1 { get; set; }
        public Nullable<decimal> cnotacred2 { get; set; }
        public Nullable<decimal> cnotacred3 { get; set; }
        public Nullable<decimal> cnotacred4 { get; set; }
        public string ctipocancelacion { get; set; }
        public Nullable<System.DateTime> cfecharetencion { get; set; }
    }
}
