//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_DEPOSITORELACION
    {
        public decimal ciddrelacobro_depd { get; set; }
        public decimal ciddrelacobrodep { get; set; }
        public string cidrelacobro { get; set; }
        public string ndeposito { get; set; }
        public string cefectivocheq { get; set; }
        public string cncheque { get; set; }
        public string cefectivo { get; set; }
        public string cbancocheque { get; set; }
        public string cfechaemision { get; set; }
        public string cmontocheque { get; set; }
        public string ccompany { get; set; }
        public decimal cgroupcomp { get; set; }
        public Nullable<double> cmontoefectivo { get; set; }
        public Nullable<double> cmontocheques { get; set; }
    }
}
