//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3TRELACCOBMCOBPENDIENTES
    {
        public string cvendedor { get; set; }
        public string cnamevendedor { get; set; }
        public short ctipocobro { get; set; }
        public decimal cidrelacobro { get; set; }
        public Nullable<System.DateTime> cfecharela { get; set; }
        public string cobservaciones { get; set; }
        public Nullable<short> caprobado { get; set; }
        public short cdelete { get; set; }
        public Nullable<short> crelalista { get; set; }
        public string ccaja { get; set; }
        public Nullable<byte> coficina { get; set; }
        public Nullable<byte> csaldado { get; set; }
        public Nullable<byte> crelafinven { get; set; }
        public string ccompany { get; set; }
        public int cgroupcomp { get; set; }
    }
}
