//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_USUARIOFULLINFO
    {
        public int cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string cuser { get; set; }
        public string cnameuser { get; set; }
        public string cpassw { get; set; }
        public string c_zona { get; set; }
        public byte cdelete { get; set; }
        public string clocked { get; set; }
    }
}
