//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_VALIDARPLANOFERTAVIGENTE
    {
        public decimal cidlistprecio { get; set; }
        public Nullable<byte> cregional { get; set; }
        public string ccompany { get; set; }
        public string cproveedor { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> cdes1 { get; set; }
        public Nullable<decimal> cdes2 { get; set; }
        public Nullable<decimal> cdes3 { get; set; }
        public decimal cprecioventamaximo { get; set; }
    }
}
