//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_VISTANOTASDESCPP
    {
        public string ccompany { get; set; }
        public decimal ccliente { get; set; }
        public Nullable<decimal> cnumdocu { get; set; }
        public string ctipodocument { get; set; }
        public Nullable<byte> cdescontada { get; set; }
        public Nullable<byte> canulado { get; set; }
        public Nullable<byte> cactivo { get; set; }
        public Nullable<byte> cimpresa { get; set; }
        public decimal cgroupcomp { get; set; }
        public decimal cidnotcredicc { get; set; }
    }
}
