//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_PLANOFERTAVENTASCONSULTA
    {
        public decimal ccodigo { get; set; }
        public string cdescripcion { get; set; }
        public string cdesdehasta { get; set; }
        public string CPROVEEDOR { get; set; }
        public string ccompany { get; set; }
        public string CPROVEEDORCONS { get; set; }
        public System.DateTime cfechalista { get; set; }
        public Nullable<byte> cregional { get; set; }
        public System.DateTime cfechadesde { get; set; }
        public System.DateTime cfechahasta { get; set; }
    }
}
