//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RELACIONVENDEDOR
    {
        public decimal cidrelacobro { get; set; }
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public string cname { get; set; }
        public string cfecharela { get; set; }
        public string c_grupo_vta { get; set; }
        public string cobservaciones { get; set; }
    }
}
