//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_PRODUCTOFULLINFO_ALL
    {
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public string cproducto { get; set; }
        public string cnamefc { get; set; }
        public string cgrupo { get; set; }
        public string csku { get; set; }
        public Nullable<decimal> ccostobruto_u1 { get; set; }
        public Nullable<decimal> ccostobruto_u2 { get; set; }
        public Nullable<decimal> ccostoneto_u1 { get; set; }
        public Nullable<decimal> ccostoneto_u2 { get; set; }
        public Nullable<byte> cventaund2 { get; set; }
        public Nullable<double> descuento1 { get; set; }
        public Nullable<double> descuento2 { get; set; }
        public Nullable<double> descuento3 { get; set; }
        public Nullable<double> cantmaxunid { get; set; }
        public decimal porcimp { get; set; }
        public string csubgrupo { get; set; }
        public string cproveedor { get; set; }
        public Nullable<int> cidproductod { get; set; }
        public Nullable<decimal> cprecioventamax { get; set; }
    }
}
