//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_PRODUCTOLOTEPMV
    {
        public string ccompany { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> ccostobruto_u1 { get; set; }
        public Nullable<double> ccontenidoma1 { get; set; }
        public Nullable<double> ccontenidoma2 { get; set; }
        public Nullable<int> cidproductod { get; set; }
        public Nullable<decimal> clistprecio1 { get; set; }
        public Nullable<decimal> clistprecio2 { get; set; }
        public Nullable<decimal> clistprecio3 { get; set; }
        public Nullable<decimal> clistprecio4 { get; set; }
        public Nullable<decimal> clistprecio5 { get; set; }
        public Nullable<decimal> clistprecio6 { get; set; }
        public string cproveedor { get; set; }
        public string ctax1 { get; set; }
        public Nullable<byte> cactivate { get; set; }
        public string csku { get; set; }
        public byte ccombocomp { get; set; }
        public string cnamefc { get; set; }
        public byte ccombogene { get; set; }
        public string cgrupo { get; set; }
        public Nullable<decimal> ccostobruto_u2 { get; set; }
        public Nullable<byte> cventaund2 { get; set; }
        public string csubgrupo { get; set; }
        public Nullable<decimal> ccostoneto_u1 { get; set; }
        public Nullable<decimal> ccostoneto_u2 { get; set; }
        public Nullable<decimal> cprecioventamax { get; set; }
    }
}
