//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RELCOBMDDD
    {
        public Nullable<decimal> cmontodeefectivo { get; set; }
        public decimal cidrelacobro { get; set; }
        public Nullable<decimal> cmontocancel { get; set; }
        public Nullable<short> ccancabono { get; set; }
        public Nullable<short> ccanctotal { get; set; }
        public string ctipodocument { get; set; }
        public decimal cnumdocu { get; set; }
        public string ccompany { get; set; }
        public Nullable<short> crelalista { get; set; }
        public Nullable<short> caprobado { get; set; }
        public decimal cgroupcompany { get; set; }
        public decimal ccliente { get; set; }
        public Nullable<decimal> Expr1 { get; set; }
        public Nullable<decimal> cmontcompretiva { get; set; }
    }
}
