//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RELACIONES_POR_USUARIO
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public short ctipocobro { get; set; }
        public decimal nrelacion { get; set; }
        public string cfecharela { get; set; }
        public string cobservaciones { get; set; }
        public Nullable<int> caprobado { get; set; }
        public Nullable<short> crelalista { get; set; }
        public string ccaja { get; set; }
        public Nullable<byte> coficina { get; set; }
        public Nullable<byte> csaldado { get; set; }
        public string cname { get; set; }
        public string cvendedorname { get; set; }
        public string ctipo { get; set; }
        public Nullable<byte> c_activo { get; set; }
        public Nullable<System.DateTime> cfecha { get; set; }
        public Nullable<byte> crelafinven { get; set; }
        public string cgerarea { get; set; }
        public string cuser { get; set; }
    }
}
