//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_JOEC_PROD
    {
        public string cproducto { get; set; }
        public string cnamefc { get; set; }
        public Nullable<decimal> ccostobruto_u1 { get; set; }
        public decimal cprecioventamax { get; set; }
        public string c_nomb_comer { get; set; }
        public string cname { get; set; }
        public string ccompany { get; set; }
    }
}
