//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_VALIDARPOFERTAREGVSPA
    {
        public decimal cidlistprecio { get; set; }
        public decimal ctiplista { get; set; }
        public string ccompany { get; set; }
        public string cproveedor { get; set; }
        public string cproducto { get; set; }
        public Nullable<double> cdescnetoreg { get; set; }
        public Nullable<double> cdesclinreg1 { get; set; }
        public Nullable<double> cdesclinreg2 { get; set; }
        public Nullable<double> cdesclinreg3 { get; set; }
        public Nullable<double> cdesclinreg4 { get; set; }
    }
}
