//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_PRECIOLISTA_PROD
    {
        public string cgroupcomp { get; set; }
        public decimal ccliente { get; set; }
        public string cproducto { get; set; }
        public Nullable<decimal> PrecioVentaU1 { get; set; }
        public Nullable<int> cidproductod { get; set; }
        public Nullable<decimal> cprecioventamax { get; set; }
        public string ccompany { get; set; }
    }
}
