//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_CHEQDEVUELTORELACION
    {
        public decimal cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string cnumcheque { get; set; }
        public string cidcheqdevuelt { get; set; }
        public decimal CodCliente { get; set; }
        public string cbancocheque { get; set; }
        public Nullable<byte> ctipocobro { get; set; }
        public string FechaCH { get; set; }
        public Nullable<decimal> cmontocheq { get; set; }
        public Nullable<decimal> cnumdocu { get; set; }
        public Nullable<decimal> cidmotivo { get; set; }
        public Nullable<System.DateTime> cfechadevcheq { get; set; }
        public string cbancochequedev { get; set; }
        public string cbanconddev { get; set; }
        public string cobservacion { get; set; }
        public Nullable<byte> cactivo { get; set; }
        public Nullable<decimal> cidnotadebitocc { get; set; }
        public Nullable<System.DateTime> cdateadd { get; set; }
        public string cuseradd { get; set; }
        public string cuserupd { get; set; }
        public Nullable<System.DateTime> cdateupd { get; set; }
        public string cuserdel { get; set; }
        public Nullable<System.DateTime> cdatedel { get; set; }
        public byte cdelete { get; set; }
        public string cidrelacobro { get; set; }
        public string Cliente { get; set; }
        public string ctipodocument { get; set; }
        public string cvendedor { get; set; }
    }
}
