//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_TRELACCOBDCHEQ
    {
        public string ccompany { get; set; }
        public decimal cgroupcomp { get; set; }
        public string cidrelacobro { get; set; }
        public decimal ciddrelacobro_cheq { get; set; }
        public string cnumcheque { get; set; }
        public string cbancocheque { get; set; }
        public string cbanconame { get; set; }
        public string cfechaemision { get; set; }
        public Nullable<double> cmontocheq { get; set; }
        public string ccheqdiatransito { get; set; }
        public Nullable<System.DateTime> cfechaadeposit { get; set; }
        public Nullable<byte> cegresotransito { get; set; }
        public short cdelete { get; set; }
        public string cmontonorelacionado { get; set; }
        public string cmontocheque { get; set; }
        public decimal ccliente { get; set; }
    }
}
