//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGP2_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VST_T3_RUTASVISITAEXCEPCIONES
    {
        public string cgroupcomp { get; set; }
        public string ccompany { get; set; }
        public string cvendedor { get; set; }
        public decimal ccliente { get; set; }
        public string c_rif { get; set; }
        public string c_nomb_comer { get; set; }
        public Nullable<byte> c_otrodiapedido { get; set; }
        public Nullable<System.DateTime> cfechaeje_ov { get; set; }
        public string c_zona { get; set; }
    }
}
